config/routes.rb
#Последний Листинг 8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb Листинг 10.1:  
#Листинг 3.37:
Rails.application.routes.draw do
    #Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 
root             'static_pages#home' 
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
resources :relationships,       only: [:create, :destroy]
resources :articles
resources :folders
resources :reports
resources :students


resources :users do #12.15
    member do
      get :following, :followers
    end
  end

get 'articles' => 'articles#index'
get 'folders'  =>   'folders/index'
#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
get 'password_resets/new'
  get 'password_resets/edit'

get 'microposts'    => 'microposts#index'
get 'students'    => 'students#index'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'referat' => 'static_pages#referat'
get 'july07' => 'static_pages#july07'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/


#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'




#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
#  devise_for :users
#  devise_for :admin_users, ActiveAdmin::Devise.config
  
#ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш

  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def hello
render html: "hello, world!"
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!--Листинг 5.11: 
Листинг 5.24: Партиал подвала со ссылками. app/views/layouts/_footer.html.erb
 -->
<footer class="footer">
  <small>
    The <a href="http://www.libr.asf.dp.ua/">libr.asf.dp.ua</a>
    by <a href="http://www.michaelhartl.com/">Sergei Agarkov</a>
  </small>
  <nav>
    <ul>
      <li><%#= link_to "About",   about_path %></li>
      <li><%#= link_to "Contact", contact_path %></li>
<li><%#= link_to "Referat", referat_path %></li> 
     <li><%#= link_to "July07", july07_path %></li>
	 <li><%#= link_to "Readme", readme_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- #Normal Листинг 5.23: Партиал заголовка со ссылками. app/views/layouts/#_header.html.erb#Листинг 8.16: Изменение ссылок шаблона для вошедших пользователей. app/views/layouts/#  _header.html.erb Листинг 9.36: Добавление URL к ссылке на список пользователей. app/views/layouts/_header.html.erb  "~/ch12_march24 to xgbua_march02 (?_CH12 bwithout)" -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
<li><%= link_to "August_04 ~/h263_aug04 -b master" %></li>
        <li><%= link_to "Home ", root_path %></li>
        <li><%#= link_to "Help", help_path %></li>
 <li><%#= link_to "Students", students_path %></li>


  <%# if logged_in? %>       #Листинг 8.16 9.4
<li><%#= link_to "signup_student", edit_student_path(current_user) %></li>
              <li class="divider"></li>                
<li><%#= link_to "Library", articles_path %></li>
               <li><%#= link_to('Bookmarks', folders_path) %></li>
              <!--  #Листинг 9.36:  -->
                         <li><%#= link_to "Users", users_path %></li>
        <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
                    <li><%#= link_to "Profile", current_user %></li>
                    <li><%#= link_to "Settings", edit_user_path(current_user) %></li>
<li><%#= link_to "stud_edit", edit_student_path(current_user) %></li>
              <li class="divider"></li>
                  <li>
                      <%#= link_to "Log out", logout_path, method: "delete" %>
                  </li>
            </ul>
          </li>


<li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Student <b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
<li><%#= link_to "allstudents" %></li>
                    <li><%#= link_to "Students", students_path %></li>
                    <li><%#= link_to "Settings", edit_user_path(current_user) %></li>

<li><%#= link_to "stud_edit", edit_student_path(current_user) %></li>
              <li class="divider"></li>
                  <li>
                      <%#= link_to "Log out", logout_path, method: "delete" %>
                  </li>
            </ul>
          </li>









   <%# else %>
          <li><%#= link_to "Log in", login_path %></li>
        <%# end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--Листинг 5.9:-app/views/layouts/_shim.html.erb -->

<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!--3.32
app/views/layouts/application.html.erb
<Листинг 4.1: Макет сайта учебного приложения.  
Листинг 4.3: Шаблон сайта с хелпером full_title. 
Листинг 5.1: Шаблон сайта с добавленными структурами. app/views/layouts/application.html.erb
Листинг 5.12: 5.15 Макет сайта с партиалом подвала. app/views/layouts/application.html.erb
Листинг 7.1:7.25 -->

<!DOCTYPE html>
<html>
  <head>
    <title><%#= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
 
 <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample
App</title>
</head>
<body>
<h1>August_04 ~/h263_aug04 -b master</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.
</p>
</body>
</html>